=== javays/freport/src/com/resources/freport-layout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.freport.org/freport-layout" 
		xmlns:tns="http://www.freport.org/freport-layout" 
		elementFormDefault="qualified">
		
	<element name="layout">
		<complexType>
			<sequence>
				<element name="table" minOccurs="1" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="row" minOccurs="1" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="cell" minOccurs="1" maxOccurs="unbounded">
											<complexType mixed="true">
												<attribute name="value" type="string"/>
												<attribute name="dataType">
													<simpleType>
														<restriction base="string">
															<pattern value="number|date"></pattern>
														</restriction>
													</simpleType>
												</attribute>
												<attribute name="pattern" type="string"/>
												<attribute name="hasParam" type="boolean"/>
									            <attribute name="width" type="positiveInteger"/>
									            <attribute name="height" type="positiveInteger"/>
									            <attribute name="rowspan" type="positiveInteger"/>
									            <attribute name="colspan" type="positiveInteger"/>
									            <attribute name="bold" type="boolean"/>
									            <attribute name="border" type="positiveInteger"/>
									            <attribute name="borderColor" type="string"/>
									            <attribute name="backgroundColor" type="string"/>
									            <attribute name="size" type="positiveInteger"/>
									            <attribute name="align">
													<simpleType>
														<restriction base="string">
															<pattern value="left|center|right"></pattern>
														</restriction>
													</simpleType>
												</attribute>
												<attribute name="valign">
													<simpleType>
														<restriction base="string">
															<pattern value="top|middle|bottom"></pattern>
														</restriction>
													</simpleType>
												</attribute>
									            <attribute name="img" type="string"/>
									            <attribute name="imgHeight" type="positiveInteger"/>
									            <attribute name="imgWidth" type="positiveInteger"/>
											</complexType>
										</element>
									</sequence>
									<attribute name="name" type="string"/>
									<attribute name="height" type="positiveInteger"/>
			                        <attribute name="maxline" type="positiveInteger"/>
			                        <attribute name="show" type="string"/>
			                        <attribute name="ds" type="string"/>
								</complexType>
							</element>
						</sequence>
						
						<attribute name="id" type="string"/>
						<attribute name="width">
							<simpleType>
								<restriction base="string">
									<pattern value="\d{1,3}%?"></pattern>
								</restriction>
							</simpleType>
						</attribute>
						<attribute name="align" type="string"/>
						<attribute name="br" type="boolean"/>
						<attribute name="show" type="string"/>
					</complexType>
				</element>
			</sequence>
			<attribute name="name" type="string"/>
		</complexType>
	</element>
</schema>

=== javays/freport/src/com/resources/tmpl_xls_bill_custom_horizontal_layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<layout xmlns="http://www.freport.org/freport-layout" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.freport.org/freport-layout freport-layout.xsd"
		name="tmpl_xls_bill_custom_horizontal">
    
    <table id="title">
        <row>
            <cell width="10"/>
			<cell width="12"/>
			<cell width="20"/>
			<cell width="20"/>
			<cell width="10"/>
			<cell width="20"/>
			<cell width="10"/>
			<cell width="20"/>
			<cell width="20"/>
			<cell width="13"/>
			<cell width="10"/>
			<cell width="10"/>
			<cell width="13"/>
			<cell width="13"/>
			<cell width="13"/>
<!-- 			<cell width="10"/> -->
<!-- 			<cell width="10"/> -->
<!-- 			<cell width="10"/> -->
			<cell width="13"/>
			<cell width="13"/>
			<cell width="13"/>
<!-- 			<cell width="10"/> -->
			<cell width="13"/>
			<cell width="13"/>
			<cell width="13"/>
<!-- 			<cell width="10"/> -->
			<cell width="13"/>
			<cell width="13"/>
			<cell width="15"/>
			<cell width="13"/>
			<cell width="13"/>
			<cell width="13"/>
			<cell width="13"/>
			<cell width="13"/>   <!-- 特安服务 -->
			<cell width="13"/>   <!-- 其它 -->
			<cell width="13"/>   
			<cell width="10"/>
			<cell width="10"/>
			<cell width="10"/>
			<cell width="15"/>
			<cell width="15"/>
			<cell width="20"/>
			<cell width="10"/>
			<cell width="15"/>
			<cell width="10"/>
			<cell width="10"/>
			<cell width="15"/>
			<cell width="10"/>
			<cell width="10"/>
			<cell width="10"/>
			<cell width="20"/>
			<cell width="10"/>
			<cell width="13"/>
			<cell width="10"/>
			<cell width="10"/>
			<cell width="15"/>
			<cell width="15"/>
			<cell width="15"/>
			<cell width="20"/>
			<cell width="10"/>
			<cell width="10"/>
			<cell width="20"/>
			<cell width="15"/>
			<cell width="20"/>
			<cell width="12"/>
			<cell width="20"/>
        </row>
        <row>
            <cell height="20" align="center" valign="middle" size="14" bold ="true" colspan="9">
                <![CDATA[
					客  户  月  结  清  单									
                ]]>
            </cell>
        </row>
        <row>
            <cell height="10"></cell>
        </row>
	    <row maxline="10">
	        <cell></cell>
			<cell colspan="5" hasParam="true" align="left">
					<![CDATA[
尊敬的 ($F{billHead.customerName}), 您好!
      $F{billHead.billStart} 至 $F{billHead.billEnd} 账单已产生，非常感谢您选择我司为您提供的服务，感谢您与
我司的真诚合作！本月发生的费用汇总说明如下（明细清单附后）：
      结算期间：$F{billHead.billStart} 至 $F{billHead.billEnd}	
      本期金额：$F{billSubTotal.s_totalDueAmtCurPriod}
      上期未付金额：$F{billSubTotal.s_unpaidFee}
      截止本月您累计应付金额：$F{billSubTotal.s_totalDueAmt}
      请您在收到本月账单后及时核对，如有疑问请及时与我司对账联系人员联系，以尽快确认；
如无异议，请及时确认账单并通知我司对账联系人员开票给您，并请您按我们合作协议约定
的时间及时安排付款，以此作为我们双方诚信合作的基石。谢谢！
					]]>
			</cell>
<!-- 			<cell></cell> -->
			<cell colspan="5" hasParam="true" bold="true">
					<![CDATA[
客户名称： $F{billHead.customerName}
                  $F{billHead.customerEnName}
月结账号： $F{billHead.custCode}
联  系  人： $F{billHead.contact}
地       区： $F{billHead.deptCode}
收  帐  员： $F{billHead.billingMembers}
币       别： $F{billHead.currency}
到  期  日： $F{billHead.dueDate}			
					]]>
			</cell>
		</row>
		
	    <row>
            <cell height="10"></cell>
        </row>
        <row height="25" show="order_count>0">
            <cell colspan="6" hasParam="true">
            		<![CDATA[
附：$F{billHead.billStart} 至 $F{billHead.billEnd}费用明细清单		
					]]>
            </cell>
        </row>
        <row height="15" name="head" show="order_count>0">
            <cell border="1" bold="true" rowspan="2" align="center" value="序号"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="日期"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="订单号码"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="运单号码"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="寄件地区"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="寄件公司名称"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="对方地区"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="对方客户名称"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="对方公司名称"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="重量\n(公斤)"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="付款方式"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="产品名称"/>
<!-- 			<cell border="1" bold="true" colspan="3" align="center" value="基础费用"/> -->
			<cell border="1" bold="true" rowspan="2" align="center" value="应收费用"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="单票折扣"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="实收费用"/>
			<cell border="1" bold="true" colspan="15" align="center" value="增值服务费"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="实收费用\n合计"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="订单类型"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="是否\n郊区件"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="订单来源"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="始发地\n(省名)"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="寄件人联系\n手机号"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="寄件人联系\n座机号"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="寄件地址"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="收件员\n工号"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="客户网络\n代码"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="客户网络\n名称"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="客户发货\n仓库"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="托寄物名称"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="托寄物\n数量"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="声明价值"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="件数"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="轻抛尺寸\n(长X宽X高)"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="目的地\n(省名)"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="目的地\n城市名"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="客户\n区域代码"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="邮政编码"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="收件人"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="收件人联系\n手机号"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="收件人联系\n座机号"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="收件地址"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="派件员\n工号"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="实际重量"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="回单单号"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="退件名称"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="退回件关联原订单号"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="退件\n派件时间"/>
			<cell border="1" bold="true" rowspan="2" align="center" value="备注"/>
        </row>
        <row height="15" name="head" show="order_count>0">
<!--             <cell border="1" bold="true" align="center" value="费用（元）"/> -->
<!-- 			<cell border="1" bold="true" align="center" value="单票折扣"/> -->
<!-- 			<cell border="1" bold="true" align="center" value="应收费用"/> -->
<!-- 			<cell border="1" bold="true" align="center" value="等通知派送"/> -->
<!-- 			<cell border="1" bold="true" align="center" value="超范围转寄"/> -->
<!-- 			<cell border="1" bold="true" align="center" value="偏远附件费"/> -->
 			<cell border="1" bold="true" align="center" value="签单返还"/>

			<cell border="1" bold="true" align="center" value="电商加急"/>
			<cell border="1" bold="true" align="center" value="节假日派送"/>
			<cell border="1" bold="true" align="center" value="买卖宝"/>
			<cell border="1" bold="true" align="center" value="保价"/>
			<cell border="1" bold="true" align="center" value="定时派送"/>
			<cell border="1" bold="true" align="center" value="保时达"/>
			<cell border="1" bold="true" align="center" value="电子验收"/>
			<cell border="1" bold="true" align="center" value="超长超重服务"/>
			<cell border="1" bold="true" align="center" value="退货"/>
			<cell border="1" bold="true" align="center" value="换货"/>
			<cell border="1" bold="true" align="center" value="保鲜服务"/>
			<cell border="1" bold="true" align="center" value="包装服务"/>
			<cell border="1" bold="true" align="center" value="特安服务"/>
			<cell border="1" bold="true" align="center" value="其它"/>
       </row>
       
       <row height="30" ds="order" show="order_count>0">
            <cell border="1" align="center" value="no"/>
			<cell border="1" align="center" value="deliveredTm"/>
			<cell border="1" align="center" value="orderNo"/>
			<cell border="1" align="center" value="waybillNo"/>
			<cell border="1" align="center" value="senderCityCode"/>
			<cell border="1" align="center" value="senderCompany"/>
			<cell border="1" align="center" value="destinationCityCode"/>
			<cell border="1" align="center" value="receiveName"/>
			<cell border="1" align="center" value="receiveCompany"/>
			<cell border="1" align="center" value="weightQty" dataType="number" pattern="0.00"/>
			<cell border="1" align="center" value="payType"/>
			<cell border="1" align="center" value="productCode"/>
			<cell border="1" align="center" value="feeAmtFreight" dataType="number" pattern="0.00"/>
			<cell border="1" align="center" value="feeRebateFreight" dataType="number" pattern="0.00"/>
			<cell border="1" align="center" value="feeDueFreight" dataType="number" pattern="0.00"/>
			
<!-- 			<cell border="1" align="center" value="feeNotify" dataType="number" pattern="0.00"/> -->
<!-- 			<cell border="1" align="center" value="feeOutOfScope" dataType="number" pattern="0.00"/> -->
